name: RNAseq-part1-bash

channels:
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
  - defaults
  - bioconda
  - conda-forge

dependencies:
  - jupyterlab=2
  - nbresuse
  - python>=3.7
  - pip
  - nodejs
 # Dataset retrieval
  - sra-tools=2.10.3
  - pigz=2.3.4
 # QC synthesis
  - multiqc=1.9
 # Preprocessing tools
  - fastqc=0.11.9
  - fastp=0.20.0
  - fastq-screen=0.13.0
 # Mapper and QC tools
  - star=2.7.5a
  - samtools=1.10
  - qualimap=2.2.2
 # Read summarizations
  - subread=2.0.1
  - stringtie
 # Analysis tools
  - r-sartools
  - htseq 
  - libgomp
  - r-irkernel
  - r-base>=3.6
  - r-tidyverse 
  - r-Matrix
  - r-lattice
  - r-fdrtool
  - r-rpart
  - r-RSQLite
  - r-gplots
  - r-locfit
  - pip:
    - bash_kernel
